/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package src;

import java.io.FileNotFoundException;
import src.Compiler.CompilerBinary;

public class App {

	public static void main(String[] args) {
			
		CompilerBinary  compiler = new CompilerBinary();

		try {
			compiler.TransformBinary();
		} catch (FileNotFoundException error) {
			
			error.printStackTrace();
		}
	
	}

}
